name = "name_1"
version = "version_1"

enabled = true

[[variable_status_hooks]]
variable_name = "variable_name_1"
path_to_script = "path_to_script_1"
prepare_step_necessary = false

[[variable_status_hooks__my_target]]
variable_name = "variable_name_1"
path_to_script = "path_to_script_1"
prepare_step_necessary = false
