name = "name_1"
version = "version_1"

enabled = true

[[links]]
name = "link_name_1"
path_to_symlink = "path_to_symlink_1"

[[links]]
name = "link_name_2"
path_to_target = "path_to_target_2"
path_to_symlink = "path_to_symlink_2"