name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Update pip to the latest version
      run: |
        python -m pip install --upgrade pip
    - name: Set up virtual a environment
      run: |
        python -m venv env
        source env/bin/activate
        echo "VIRTUAL ENV: ${VIRTUAL_ENV}"
    - name: Initialize testing system
      run: |
        make init
    - name: Run code quality checks
      run: |
        make check
    - name: Run test suite
      run: |
        make test
