name: linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.8.9"
    - name: Update pip to the latest version
      run: |
        python -m pip install --upgrade pip
    - name: Set up virtual a environment
      run: |
        python -m venv env
        source env/bin/activate
        echo "VIRTUAL_ENV='${VIRTUAL_ENV}'"
    - name: Initialize testing system
      run: |
        source env/bin/activate
        echo "VIRTUAL_ENV='${VIRTUAL_ENV}'"
        make init
        make dev_init
    - name: Run code quality checks
      run: |
        source env/bin/activate
        echo "VIRTUAL_ENV='${VIRTUAL_ENV}'"
        make check
    - name: Run test suite
      run: |
        source env/bin/activate
        echo "VIRTUAL_ENV='${VIRTUAL_ENV}'"
        make test
